//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int stud_ID { get; set; }
        public string stud_name { get; set; }
        public string stud_Surname { get; set; }
        public System.DateTime DaateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string EducationLevel { get; set; }
        public string Address { get; set; }
        public int contact { get; set; }
        public string Email { get; set; }
        public byte[] resume { get; set; }
        public byte[] qrImage { get; set; }
    }
}
